### ISSUE TITLE
Scroll doesn't restore on backwards navigation

### ISSUE THREAD

**Issue by silouanwright** [faceyspacey/redux-first-router-restore-scroll#14]
I'm having this issue locally, but I was also able to recreate from a forked version of the codesandbox demo. I did have to remove the Transition components as they don't allow you to scroll on those pages.

https://codesandbox.io/s/jp3ym7p935

To test this, scroll down on HOME, navigate to another page, then press the back button. The page will return with the exact scroll it had.

The code does execute there inside that block, it just doesn't honor the booleans. I'll probably do a window.scrollToTop(0,0) and then return false inside there until this is patched, not the end of the world.

**Comment by faceyspacey** [comment]
it worked perfectly for me. i had to make the browser window small to have anything to scroll.

...oh i see, you returned true and expected scroll to top. 

it looks like i misinterpreted how the scroll-behavior library depended on works, as i was only using this for the more complex scenario of remembering positions. 

it looks like u just return `[0, 0]` there instead of true:

https://github.com/taion/scroll-behavior#custom-scroll-behavior

feel free to PR the docs. ...i've been putting a lot of work in your "HONOR PROMISES" stuff from the main RFR lib. there's a lot of new stuff. will have more to report back soon.

**Comment by faceyspacey** [comment]
https://codesandbox.io/s/oq29jmn176

**Comment by silouanwright** [comment]
@faceyspacey thanks. I'm making a return back to your library to see what you introduced! Is "Honor promises" apart of Rudy?

**Comment by faceyspacey** [comment]
Rudy next which isn’t documented yet and almost out. It’s not on npm yet :)
