### ISSUE TITLE
Error on iOS <= 10 Safari/Chrome inCognito

### ISSUE THREAD

**Issue by matthemsteger** [faceyspacey/redux-first-router-restore-scroll#17]
There is an error that is unhandled that can cause problems on iOS 10 and below with Safari and Chrome when in inCognito mode. In that case storing anything to localStorage can cause an error to be thrown that is unhandled by the library (since the quota for localStorage is set to 0). Note that it is *possible* for any call to add data to localStorage to fail if you stuff too much in there, but that is uncommon for most use cases, which is why most people dont try to catch any error there.

I am unsure how to best handle this without bloating the library code for this edge case (by adding in memory storage in that case) or by throwing out the behavior (by swallowing the error). Also, this is fixed in iOS 11, so thanks Apple for making this a mess 👎 

For now I will probably issue a PR for custom `stateStorage` object being allowed. This will allow consumers of the library to get around this problem if necessary.

**Comment by faceyspacey** [comment]
yea, a plain in-memory fallback would be a good fix. The only case it doesn't solve is if you back off or forward off on to another site and return--it will have lost the state stored in memory and won't restore scroll.

That said for the next version of RFR, I have a solution: you can in fact store everything on every history entry's state, and use it as sessionStorage! i.e. `window.history.state` isn't disabled in those situations.

One other thing: are you sure about chrome in cognito mode? You sure it's not just safari. I did tests on chrome on the desktop (osx) and incognito mode doesn't turn off session or local storage:

![screen shot 2017-10-16 at 2 08 37 pm](https://user-images.githubusercontent.com/154732/31635432-8a4274d4-b27b-11e7-98f1-81656d27c62a.png)

My previous assessments are that it's just Safari private browsing mode and when cookies are turned off. 

----
Since the next version of RFR will have built-in support for this stuff, I think it may be best to couple this package to RFR even more by saving through RFR--that way it can use the `history-storage` fallback I just described. But the PR you mentioned is still probably smart, as it may be a while before we can connect all these dots.

**Comment by matthemsteger** [comment]
Ah, make sense. I will put together a PR to allow that customization to get around the issue for now.

Actually, we found the issue with Chrome on iOS 10 and duplicated it on Safari iOS 10. OSX is fine, it operates correctly .. it's only the Safari engine on iOS (which Chrome iOS uses) on iOS 10 and below. Apple fixed it apparently in iOS 11 to behave like all other browsers (Web Storage API works, its just "private" and cleaned up after the private/incognito session is done).

**Comment by faceyspacey** [comment]
it's also important simply because some people turn off cookies, which also turns of local and session storage. the percent is less than 1%, but still.
